### ISSUE TITLE
Python 3.8.3 support?

### ISSUE THREAD

**Issue by barbequesauce** [kongr45gpen/supybot-github#28]
`WARNING 2020-06-13T16:44:30 Failed to load Github: This plugin may be incompatible with your current Python version. If this error is appearing with stock Supybot plugins, remove the stock plugins directory (usually ~/Limnoria/plugins) from 'config directories.plugins'.`

Any idea why it's not loading for python 3.8.3?

**Comment by allejo** [comment]
The current master branch only supports Python 2. For Python 3 support, take a look at PR #27.

**Comment by kongr45gpen** [comment]
Python 3 support was merged in the master branch!
